name: Labeling new issue
on:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-not-allowed: '["crash","duplicate","feedback","bug","wontfix"]'
